name: easy_admob_ads_flutter
description: A simple and flexible Flutter package to integrate AdMob ad formats with minimal setup.
version: 1.0.2
homepage: https://github.com/huzaibsayyed/easy_admob_ads_flutter
repository: https://github.com/huzaibsayyed/easy_admob_ads_flutter
issue_tracker: https://github.com/huzaibsayyed/easy_admob_ads_flutter/issues
platforms:
  android:
  ios:
topics:
  - admob
  - ads
  - google-mobile-ads
  - google-admob-flutter
  - monetization
screenshots:
  - description: 'iPhone Displays various AdMob ad types integrated using the easy_admob_ads_flutter package.'
    path: example/screenshots/demo-iphone.png
  - description: 'iPad Displays various AdMob ad types integrated using the easy_admob_ads_flutter package.'
    path: example/screenshots/demo-ipad.png
  - description: 'Demonstrates integration of all major AdMob ad types using easy_admob_ads_flutter.'
    path: example/screenshots/demo.gif

environment:
  sdk: ^3.10.8
  flutter: ^3.38.9

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^7.0.0
  shared_preferences: ^2.5.3
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0